#! /bin/bash  -ex

cd ~
mkdir tmp
cd tmp/

yum install -y emacs gcc gcc-c++ python3 python3-devel htop wget git libpng-devel libjpeg-devel libcurl-devel make gcc-gfortran tar


git clone https://github.com/healpy/cfitsio.git
cd cfitsio && git checkout 8838182 && ./configure --prefix=/usr/local && make && make install
cd ..
rm -rf cfitsio

wget http://tdc-www.harvard.edu/software/wcstools/wcstools-3.9.5.tar.gz
tar -zxf wcstools-3.9.5.tar.gz
cd wcstools-3.9.5 && make
mkdir -p /usr/local/include/libwcs
cd ..
cp wcstools-3.9.5/libwcs/*.h /usr/local/include/libwcs
cp wcstools-3.9.5/libwcs/*.a /usr/local/lib
cd ..
rm -rf wcstools-3.9.5*

# export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib
export LDFLAGS="-L/usr/local/lib ${LDFLAGS}"

git clone https://github.com/spacetelescope/fitscut
cd fitscut && git checkout c76680d && ./configure && make && make install
cd ..
rm -rf fitscut

echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig

