#! /bin/sh -eu

output_dir=${1:-"logs"}
bucket=${2:-"s3://hstdp-batch-outputs"}

mkdir -p $output_dir

./get_logs $bucket > $output_dir/logs.txt

for log in `cat $output_dir/logs.txt`; do
    output=$output_dir/`dirname $log`
    mkdir -p $output
    aws s3 cp $bucket/$log $output
done
