#! /usr/bin/env python
#-*- python -*-
import sys
import random

def main(count, ipppssoots_file):
    with open(ipppssoots_file) as inp:
          ipppssoots = inp.read().splitlines()
          assert count <= len(ipppssoots)
          sample = random.sample(ipppssoots, count)
          for id in sample:
              print(id)


if __name__ == "__main__":
   # <count> <ipppssoots_file>
   main(int(sys.argv[1]), sys.argv[2])
