#! /usr/bin/env python

"""This script is used to convert event data copied from CloudWatch to YAML,
with the account ID and bucket adapted for moto testing.

Strictly speaking the event format coming from CloudWatch logs (at
least where I found them) is Python and will not load using the json
module due to e.g. use of single quotes.  Hence, while the files here
are named .json they're loaded with python's literal_eval().

"""

import sys
import json
import re
import ast

import yaml


def scrub_file(input_file):
    output_file = input_file.replace(".json", ".yaml")

    with open(input_file) as file:
        text = file.read()

    account = re.search(r"'account': '([\dx]+)'", text).groups()[0]
    bucket = re.search(r"s3://([a-zA-ZX0-9\-]+)", text).groups()[0]

    text = re.sub(account, "x" * len(account), text)
    text = re.sub(bucket, "calcloud-processing-moto", text)

    d = ast.literal_eval(text)

    with open(input_file, "w+") as file:
        file.write(text)

    with open(output_file, "w+") as file:
        yaml.dump(d, file)


if __name__ == "__main__":
    for filename in sys.argv[1:]:
        scrub_file(filename)
