#! /bin/sh

s3_output_path=$1
from_type=$2
to_type=$3

from="${s3_output_path}/messages/${from_type}/"

for dataset in `aws s3 ls ${from} | awk '{print $4;}'`
do
    from_path=${from}${dataset}
    to_path=${s3_output_path}/messages/${to_type}/${dataset}
    aws s3 mv ${from_path} ${to_path}
done
