#! /bin/bash

ECR_ARN=$1   # get this from the ECR console or Terraform state, e.g 1234567890.dkr.ecr.us-east-1.amazonaws.com/caldp

awsudo ${ADMIN_ARN}  aws ecr get-login-password --region us-east-1 | docker login --password-stdin --username AWS $ECR_ARN

