#! /bin/bash

# For non-AWS desktop use based on pip install.  Docker must wrap this.

# Configure CRDS for HST serverless mode using readonly /grp/crds/cache
export CRDS_SERVER_URL=https://hst-serverless-mode.stsci.edu
export CRDS_PATH=/grp/crds/cache
export CRDS_READONLY_CACHE=1

source hstdputils-cal-env

python -m hstdputils.process none  $*

