#! /bin/bash

# Run commands in the HSTDP container.
# Expose $HOME as $HOME in the container.
# Map (jupyter lab) container port 8888 to docker host port 8888.

export HSTDP_DOCKER_IMAGE=jaytmiller/hstdp-calcloud:latest 

docker run --rm -it -p 8888:8888 --mount type=bind,source=$HOME,target=/home/developer $HSTDP_DOCKER_IMAGE $*






