from calcloud import io
from calcloud import hst
from calcloud import lambda_submit


RESCUE_TYPES = ["error", "terminated"]


def lambda_handler(event, context):

    # Decode the S3 event message generated by the message write operation.
    # See S3 docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html
    bucket_name = event["Records"][0]["s3"]["bucket"]["name"]
    message = event["Records"][0]["s3"]["object"]["key"]
    ipst = message.split("-")[-1]
    print(f"received {message} on bucket s3://{bucket_name}")
    assert hst.IPPPSSOOT_RE.match(ipst) or ipst == "all", "Bad ipppssoot value: " + repr(ipst)

    comm = io.get_io_bundle(bucket_name)
    if ipst == "all":
        comm.messages.delete("rescue-all")
        fail_ipsts = set()
        for type in RESCUE_TYPES:
            ipsts = [msg.split("-")[-1] for msg in comm.messages.list(f"{type}-all")]
            fail_ipsts |= ipsts
        for this in fail_ipsts:
            comm.messages.put(f"rescue-{this}")
    else:
        if comm.inputs.listl(ipst): # lambda_submit.main clears outputs and all messages
            lambda_submit.main(ipst, bucket_name)
        else:
            print("No inputs for", ipst, "cannot rescue.")
