name: merge-main-to-develop
on:
  push:
    branches:
      - main

jobs:
  merge-main-to-develop:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: .github/scripts/merge-main-to-develop.sh
  tag-latest:
    runs-on: ubuntu-26.04
    needs: merge-main-to-develop
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - run: .github/scripts/tag-latest.sh
