name: merge-main-to-develop
on:
  push:
    branches:
      - main

jobs:
  merge-main-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: .github/scripts/merge-main-to-develop.sh
  tag-latest:
    runs-on: ubuntu-latest
    needs: merge-main-to-develop
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: .github/scripts/tag-latest.sh
      