name: merge-main-to-develop
on:
  push:
    branches:
      - main

jobs:
  merge-main-to-develop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - run: .github/scripts/merge-main-to-develop.sh
  tag-latest:
    runs-on: ubuntu-22.04
    needs: merge-main-to-develop
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
      - run: .github/scripts/tag-latest.sh
      
