name: check-merge-main2develop
on:
  pull_request:
    branches:
      - main

jobs:
  check-merge-main2develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: .github/scripts/check-merge-main2develop.sh
      