name: pytest

on: [push, pull_request]

jobs:
  coverage:
    name: code coverage check
    runs-on: ubuntu-18.04

    steps:
      - name: set up python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12

      - name: checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: pip install .[dev]

      - name: run pytest code coverage check
        run: | 
          pytest \
            --verbose \
            --cov=calcloud \
            --cov=lambda/AmiRotation \
            --cov=lambda/batch_events \
            --cov=lambda/blackboard \
            --cov=lambda/broadcast \
            --cov=lambda/JobClean \
            --cov=lambda/JobDelete \
            --cov=lambda/JobPredict \
            --cov=lambda/JobRescue \
            --cov=lambda/ModelIngest \
            --cov=lambda/refreshCacheLogs \
            --cov=lambda/refreshCacheSubmit \
            --cov=lambda/s3_trigger \
            --cov-fail-under 30 \
            -rP
            --deselect tests/test_model_ingest.py

  pytest:
    name: pytest
    runs-on: ubuntu-18.04

    steps:
      - name: set up python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12

      - name: checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: pip install .[dev]

      - name: run pytest
        run: pytest -rP --deselect tests/test_model_ingest.py
  
  pytestmi:
    name: pytest model ingest
    runs-on: ubuntu-18.04

    steps:
      - name: set up python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12

      - name: checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: | 
          pip install .[dev]
          pip install numpy

      - name: run pytest
        run: pytest -rP -k 'test_model_ingest'