name: pytest

on: [push, pull_request]

jobs:
  coverage:
    name: code coverage check
    runs-on: ubuntu-20.04

    steps:
      - name: set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install .[dev]
          pip install numpy scikit-learn tensorflow --upgrade-strategy only-if-needed

      - name: run pytest code coverage check
        run: |
          pytest \
            --verbose \
            --cov=calcloud \
            --cov=lambda/AmiRotation \
            --cov=lambda/batch_events \
            --cov=lambda/blackboard \
            --cov=lambda/broadcast \
            --cov=lambda/JobClean \
            --cov=lambda/JobDelete \
            --cov=lambda/JobPredict \
            --cov=lambda/JobRescue \
            --cov=lambda/ModelIngest \
            --cov=lambda/refreshCacheLogs \
            --cov=lambda/refreshCacheSubmit \
            --cov=lambda/s3_trigger \
            --cov-fail-under 30 \

  pytest:
    name: pytest
    runs-on: ubuntu-20.04

    steps:
      - name: set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: checkout code
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install .[dev]
          pip install numpy scikit-learn==1.4.1.post1 tensorflow==2.15.0.post1 --upgrade-strategy only-if-needed

      - name: run pytest
        run: pytest -rP