name: tag-stable
on:
  push:
    branches:
      - main

jobs:
  update-stable-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - run: .github/scripts/tag-stable.sh
