name: tag-latest
on:
  push:
    branches:
      - develop

jobs:
  update-latest-tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/tag-latest.sh